//
// Created by Khurram Javed on 2021-07-22.
//

#ifndef TESTS_INCLUDE_FEEDFORWARD_TESTCASE_H
#define TESTS_INCLUDE_FEEDFORWARD_TESTCASE_H

bool feedforwadtest();

#endif  // TESTS_INCLUDE_FEEDFORWARD_TESTCASE_H
